version: 0.0
os: linux

files: 
  - source: /
    destination: /opt/codedeploy
hooks:
  BeforeInstall:
    - location: Scripts/BeforeInstall.sh
  AfterInstall:
    - location: Scripts/AfterInstall.sh
      timeout: 60
  ApplicationStart:
    - location: Scripts/ApplicationStart.sh
      timeout: 60
  ValidateService:
    - location: Scripts/ValidateService.sh
      timeout: 60
  