Resources:
  RandomNameRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /service-role/
      RoleName: scorekeep-lambda

  RandomNameFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: "PLACEHOLDER"
      Description: "Generate random names"
      Environment:
        Variables:
          REGION_NAME: {"Ref" : "AWS::Region"}
          TOPIC_ARN: "PLACEHOLDER"
      FunctionName: random-name
      Handler: index.handler
      Role: { "Fn::Join": [ "", [ "arn:aws:iam::",{"Ref" : "AWS::AccountId"},":role/service-role/scorekeep-lambda" ] ] }
      Runtime: nodejs4.3
